package rm.dao;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.SQLException;
import java.sql.Statement;

public class TestDatabaseSetup {

    private static final String DB_URL = "jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1";
    private static final String DB_USER = "sa";
    private static final String DB_PASSWORD = "";

    private static Connection connection;

    /**
     * Inizializza il database H2 in-memory con lo schema necessario
     */
    public static void setupTestDatabase() throws SQLException {
        connection = DriverManager.getConnection(DB_URL, DB_USER, DB_PASSWORD);
        createSchema();
    }

    /**
     * Crea lo schema del database per i test
     */
    private static void createSchema() throws SQLException {
        try (Statement stmt = connection.createStatement()) {
            // Tabella menu_items
            stmt.execute("""
                 CREATE TABLE IF NOT EXISTS menu_items (
                         id INT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
                         nome VARCHAR(255) NOT NULL,
                         tipologia VARCHAR(100),
                         prezzo_vendita DECIMAL(10,2),
                         costo_realizzazione DECIMAL(10,2),
                         allergeni TEXT
                     )
            """);

            // Tabella users
            stmt.execute("""
                CREATE TABLE IF NOT EXISTS users (
                    username VARCHAR(100) PRIMARY KEY,
                    password VARCHAR(255) NOT NULL,
                    role VARCHAR(50) NOT NULL,
                    kitchen_preferences TEXT
                )
            """);

            // Altri indici e vincoli
            stmt.execute("CREATE INDEX IF NOT EXISTS idx_tipologia ON menu_items(tipologia)");
        }
    }

    /**
     * Pulisce i dati dalle tabelle mantenendo lo schema
     */
    public static void cleanDatabase() throws SQLException {
        try (Statement stmt = connection.createStatement()) {
            stmt.execute("DELETE FROM menu_items");
            stmt.execute("DELETE FROM users");
            // Reset sequences
            stmt.execute("ALTER TABLE menu_items ALTER COLUMN id RESTART WITH 1");
        }
    }

    /**
     * Ottiene la connessione al database di test
     */
    public static Connection getConnection() {
        return connection;
    }

    /**
     * Chiude la connessione al database di test
     */
    public static void closeDatabase() throws SQLException {
        if (connection != null && !connection.isClosed()) {
            connection.close();
        }
    }

    /**
     * Inserisce dati di test standard
     */
    public static void insertTestData() throws SQLException {
        try (Statement stmt = connection.createStatement()) {
            stmt.execute("""
                INSERT INTO menu_items (nome, tipologia, prezzo_vendita, costo_realizzazione, allergeni)
                VALUES 
                    ('Spaghetti Carbonara', 'Primi', 12.50, 4.20, 'Uova, Latticini'),
                    ('Pizza Margherita', 'Pizze', 8.00, 2.50, 'Glutine, Latticini'),
                    ('Tiramisù', 'Dolci', 6.00, 2.00, 'Uova, Glutine, Latticini')
            """);
        }
    }
}